// generado por tools/generate-audio.mjs — no editar a mano
window.UI_AUDIO = {
  "Mundo de la Alegría": "audio/ui/73e98cc088.mp3",
  "¡Bienvenido al Mundo de la Alegría! El reino ha perdido su luz brillante… Solo tú puedes ayudar a recuperarla completando los retos.": "audio/ui/ae7b7c00f5.mp3",
  "¡Felicidades! Has recuperado la Energía de la Alegría": "audio/ui/330af4dbca.mp3",
  "Comenzar misión": "audio/ui/578cf8dd2c.mp3",
  "Haz clic en el niño que está feliz": "audio/ui/9ecc73ae84.mp3",
  "¡Muy bien! Has encontrado la alegría": "audio/ui/8995c9642c.mp3",
  "Intenta de nuevo, mira bien las caritas": "audio/ui/a8c99133f9.mp3",
  "Selecciona las situaciones que te hacen sentir feliz": "audio/ui/03d4e953bf.mp3",
  "¡La alegría aparece cuando hacemos cosas que nos gustan!": "audio/ui/fa6f8bc699.mp3",
  "Niño jugando": "audio/ui/3f0a0ce2c8.mp3",
  "Niño llorando": "audio/ui/4fdbbee8cd.mp3",
  "Niño compartiendo": "audio/ui/17c6e17a28.mp3",
  "Elige lo que te hace feliz": "audio/ui/316177731c.mp3",
  "¿Qué te hace feliz?": "audio/ui/9fb9f5058f.mp3",
  "¡Qué bonito! Todos sentimos alegría de formas diferentes": "audio/ui/636105036a.mp3",
  "Jugar": "audio/ui/06d92aef37.mp3",
  "Familia": "audio/ui/9772bae698.mp3",
  "Amigos": "audio/ui/bceee15371.mp3",
  "Tu amigo está triste… ¿qué haces?": "audio/ui/b0b1d491ce.mp3",
  "¡Compartir alegría hace el mundo mejor!": "audio/ui/e08c92c934.mp3",
  "Abrazarlo": "audio/ui/65f1be8a74.mp3",
  "Ignorarlo": "audio/ui/3b3f838fab.mp3",
  "Compartir un juguete": "audio/ui/ef0815ee0b.mp3",
  "Mundo de la Tristeza": "audio/ui/84b0498c12.mp3",
  "El cielo del reino está gris… Lee esta historia y ayuda a recuperar la calma.": "audio/ui/a3cda9d0ef.mp3",
  "La tristeza nos ayuda a expresar lo que sentimos… y no estamos solos": "audio/ui/b0c06250a8.mp3",
  "Leer el cuento": "audio/ui/0b954a73c0.mp3",
  "Escucha el cuento y luego responde": "audio/ui/12c60a3f2f.mp3",
  "¡Muy bien! Entendiste la historia y la tristeza": "audio/ui/2677f0c2ce.mp3",
  "Había una vez una pequeña nube que vivía en el cielo del Reino de las Emociones. Era blanca, esponjosa y le gustaba flotar muy alto. Pero un día empezó a sentirse diferente: ya no quería jugar, ni moverse, ni brillar. Estaba triste, pero no lo entendía. Intentó esconderse detrás de otras nubes, pero la tristeza seguía ahí. Entonces una gotita cayó de su cuerpo, luego otra, y otra más: la nube estaba llorando. \"No quiero llorar\", dijo, \"llorar es feo\". Pero no pudo detener sus lágrimas. En ese momento, una nube grande y suave se acercó: \"Está bien llorar. A veces, llorar nos ayuda a sentirnos mejor. Cuando estás triste puedes llorar, puedes hablar y puedes pedir un abrazo\". La pequeña nube dejó de esconderse y lloró sin miedo. Poco a poco se sintió más ligera y tranquila, y ya no estaba sola. Entendió que la tristeza también es una emoción, que está bien sentirla, y que cuando la expresamos podemos sentirnos mejor. Y el cielo volvió a llenarse de calma y colores.": "audio/ui/83589c9227.mp3",
  "¿Cómo se sentía la nube?": "audio/ui/3cd7cca793.mp3",
  "Feliz": "audio/ui/a9420e143b.mp3",
  "Triste": "audio/ui/d7d0c67216.mp3",
  "Enojada": "audio/ui/4a047f9cc6.mp3",
  "¿Por qué estaba triste?": "audio/ui/96cb87c29e.mp3",
  "Estaba sola": "audio/ui/826dfe5de1.mp3",
  "Estaba jugando": "audio/ui/b771043adb.mp3",
  "¿Qué hizo la nube?": "audio/ui/c79fd14f71.mp3",
  "Lloró": "audio/ui/63b4a59136.mp3",
  "Se escondió": "audio/ui/fc2946946d.mp3",
  "¿Qué la ayudó?": "audio/ui/b231af4f0e.mp3",
  "Hablar con alguien": "audio/ui/a1d9ea166e.mp3",
  "Ignorar lo que sentía": "audio/ui/3069649f44.mp3",
  "Haz clic en quien está triste": "audio/ui/410641adf9.mp3",
  "¡Muy bien! Reconociste la tristeza": "audio/ui/cd5ff051dc.mp3",
  "¿Qué hago cuando estoy triste?": "audio/ui/0c9af6d20a.mp3",
  "Está bien expresar la tristeza": "audio/ui/20c400c78a.mp3",
  "Lloro": "audio/ui/1edbfbcb39.mp3",
  "Busco ayuda": "audio/ui/7bb6b70f98.mp3",
  "Me río": "audio/ui/eb7b8c1bc1.mp3",
  "¿Qué puedo hacer cuando estoy triste?": "audio/ui/74a919c6ce.mp3",
  "¿Qué puedo hacer?": "audio/ui/e44d433265.mp3",
  "Hablar y pedir un abrazo nos ayuda mucho": "audio/ui/7ec652efee.mp3",
  "Abrazar": "audio/ui/f09cc4d9db.mp3",
  "Guardarlo todo": "audio/ui/01199f3c30.mp3",
  "Mundo del Enojo": "audio/ui/61c6a175fb.mp3",
  "Un volcán está a punto de explotar… El enojo necesita ser controlado.": "audio/ui/0c55fe54e5.mp3",
  "¡Has calmado el volcán!": "audio/ui/c047e41882.mp3",
  "¿Quién está enojado?": "audio/ui/9318c59cee.mp3",
  "¡Muy bien! Ese es el enojo": "audio/ui/565acd7698.mp3",
  "Intenta de nuevo, mira sus cejas y su boca": "audio/ui/dcf3eb89b5.mp3",
  "¿Qué causa el enojo?": "audio/ui/cbb9387a21.mp3",
  "¡Eso es! A veces el enojo aparece cuando algo no nos gusta": "audio/ui/f2896a8a8a.mp3",
  "Quitar un juguete": "audio/ui/cfc305c754.mp3",
  "No dejar jugar": "audio/ui/3e03eaee07.mp3",
  "Dar un regalo": "audio/ui/92210f7da4.mp3",
  "Haz clic en cada color para aprender qué hacer cuando te sientes enojado": "audio/ui/3aae70a095.mp3",
  "¡Muy bien! Ahora sabes cómo controlar el enojo": "audio/ui/f9cfaca8f4.mp3",
  "PARAR": "audio/ui/13a85e5f40.mp3",
  "ALTO. Detente un momento. No grites ni pegues.": "audio/ui/f6bd1dc853.mp3",
  "PENSAR": "audio/ui/821a81ba3e.mp3",
  "PIENSA. Respira profundo. Cuenta hasta 5. ¿Qué puedes hacer?": "audio/ui/5911e409c0.mp3",
  "ACTUAR": "audio/ui/d2748cdb9b.mp3",
  "ACTÚA. Habla con calma. Pide ayuda. Busca una solución.": "audio/ui/9b08321bbd.mp3",
  "¿Qué haces primero cuando estás enojado?": "audio/ui/158941ae91.mp3",
  "Pensar": "audio/ui/8d803e6309.mp3",
  "Parar": "audio/ui/af45a0df23.mp3",
  "Gritar": "audio/ui/d8c0652f50.mp3",
  "¿Y después de parar?": "audio/ui/a2456492fc.mp3",
  "¿Qué te ayuda a calmar el volcán?": "audio/ui/fdb2e8f930.mp3",
  "¿Qué te ayuda a calmarte?": "audio/ui/40f51ac840.mp3",
  "Respirar profundo": "audio/ui/04edc29e7d.mp3",
  "Contar hasta 5": "audio/ui/78fb43299e.mp3",
  "Golpear": "audio/ui/385c7711ca.mp3",
  "Mundo del Miedo": "audio/ui/4f1ffcb68c.mp3",
  "El reino está un poco oscuro… pero no todo lo que da miedo es peligroso. Lee esta historia y conviértete en valiente.": "audio/ui/e9ecca384f.mp3",
  "¡Has recuperado la energía del valor!": "audio/ui/8b57844749.mp3",
  "¡Muy bien! Entendiste el miedo y cómo enfrentarlo": "audio/ui/adb373b7e2.mp3",
  "Había una vez un niño llamado Mateo. Le gustaba jugar, reír y pasar tiempo con su familia. Pero había algo que no le gustaba nada: le daba miedo la oscuridad. Cuando llegaba la noche y apagaban la luz, su corazón latía más rápido. \"¿Y si hay un monstruo? ¿Y si algo está escondido?\", pensaba, y se tapaba con su cobija. Pero el miedo seguía ahí. Una noche, su mamá entró: \"El miedo es una emoción y todos lo sentimos alguna vez. Pero no todo lo que parece miedo es peligroso\". Le dio una pequeña linterna: \"Esta luz puede ayudarte a ver mejor, y también puedes llamarme si me necesitas\". Mateo respiró profundo. Esa noche encendió su linterna, miró alrededor y descubrió que no había monstruos: solo su juguete, una silla y su osito. Mateo sonrió. Desde ese día entendió que sentir miedo está bien, y que ser valiente no es no tener miedo, sino enfrentar lo que sentimos paso a paso, pidiendo ayuda y respirando profundo. Y poco a poco, la oscuridad dejó de ser tan aterradora.": "audio/ui/58757f48cb.mp3",
  "¿Cómo se sentía el niño?": "audio/ui/19065b4c47.mp3",
  "Asustado": "audio/ui/e392782525.mp3",
  "Enojado": "audio/ui/630a944539.mp3",
  "¿Qué le daba miedo?": "audio/ui/b7bc0e2665.mp3",
  "La oscuridad": "audio/ui/7b92590957.mp3",
  "¿Qué hizo el niño?": "audio/ui/62bca98546.mp3",
  "Encendió una luz": "audio/ui/e247567907.mp3",
  "Se quedó solo llorando": "audio/ui/42d17361b0.mp3",
  "¿Qué lo ayudó?": "audio/ui/9ca591f88f.mp3",
  "Pedir ayuda": "audio/ui/247407f625.mp3",
  "Esconderse siempre": "audio/ui/752545062d.mp3",
  "Haz clic en quien tiene miedo": "audio/ui/788c5bde6d.mp3",
  "¡Correcto! Mira sus ojos y su expresión": "audio/ui/3ba06c0ac8.mp3",
  "Observa sus ojos y su expresión": "audio/ui/0d393065d9.mp3",
  "¿Qué cosas pueden dar miedo?": "audio/ui/329fac69e7.mp3",
  "Sentir miedo de algunas cosas es normal": "audio/ui/7a0da27904.mp3",
  "Oscuridad": "audio/ui/5052cb6a8b.mp3",
  "Ruidos fuertes": "audio/ui/f38e144cda.mp3",
  "Cumpleaños": "audio/ui/23dbaffa6f.mp3",
  "¿Qué puedes hacer cuando sientes miedo?": "audio/ui/235ae09ba0.mp3",
  "Ser valiente no es no tener miedo… es aprender a enfrentarlo": "audio/ui/77a40fdcb7.mp3",
  "Encender la luz": "audio/ui/2c208e2529.mp3",
  "Mundo de la Sorpresa": "audio/ui/b2fad4abfd.mp3",
  "¡Algo inesperado pasó en el reino! Ayúdanos a descubrir la emoción de la sorpresa.": "audio/ui/411e5e2f6d.mp3",
  "¡Has descubierto el poder de la sorpresa!": "audio/ui/2fc48a4cf8.mp3",
  "Haz clic en quien está sorprendido": "audio/ui/88cc2a2170.mp3",
  "¡Esa es la cara de sorpresa!": "audio/ui/7fd543bfa0.mp3",
  "Mira bien, la sorpresa abre mucho los ojos y la boca": "audio/ui/fd85dea0a6.mp3",
  "Lleva cada situación a su caja": "audio/ui/dd3e78fab8.mp3",
  "¡Muy bien! No todas las sorpresas son iguales": "audio/ui/1f8801dc9a.mp3",
  "Un regalo inesperado": "audio/ui/13dd6273fb.mp3",
  "Una fiesta sorpresa": "audio/ui/019f08377e.mp3",
  "Un globo que explota fuerte": "audio/ui/0994ca936c.mp3",
  "Tropezar de repente": "audio/ui/2df2548388.mp3",
  "¿Cómo es la cara de sorpresa?": "audio/ui/0761108f0d.mp3",
  "¡Correcto! Esa es la sorpresa": "audio/ui/641ab3d347.mp3",
  "Intenta de nuevo, mira los ojos bien abiertos": "audio/ui/a363b8ce53.mp3",
  "¿Qué hago cuando me sorprendo?": "audio/ui/f54cf23130.mp3",
  "¡Muy bien! Respirar y observar nos ayuda": "audio/ui/f75095d1b5.mp3",
  "Respiro y observo": "audio/ui/ad5b27fe9b.mp3",
  "Me asusto y grito": "audio/ui/cbaeff036c.mp3",
  "Pregunto qué pasó": "audio/ui/0b11a6affe.mp3",
  "Mundo del Asco": "audio/ui/ac02288e26.mp3",
  "El reino necesita cuidarse. Descubre cómo el asco nos protege y nos ayuda a cuidarnos.": "audio/ui/dc7a7a0659.mp3",
  "El asco nos protege y nos ayuda a cuidarnos": "audio/ui/56d62dbf54.mp3",
  "Haz clic en quien siente asco": "audio/ui/df73e22e34.mp3",
  "¡Eso es! Esa es la cara de asco": "audio/ui/e3cd6536ea.mp3",
  "Mira la nariz arrugada y la boca": "audio/ui/b3481e3a00.mp3",
  "¿De qué nos cuida el asco?": "audio/ui/a9f9bdf25b.mp3",
  "¡Muy bien! El asco nos avisa de cosas que pueden hacernos daño": "audio/ui/82df22ae08.mp3",
  "Comida dañada": "audio/ui/cefbf6eb2d.mp3",
  "Basura": "audio/ui/7821f06111.mp3",
  "Una flor": "audio/ui/355a44fac3.mp3",
  "Barro sucio": "audio/ui/88831fa58f.mp3",
  "¿Qué hago cuando algo me da asco?": "audio/ui/f39f7a5d53.mp3",
  "¿Qué hago?": "audio/ui/aea97f2a56.mp3",
  "¡Correcto! Alejarse y avisar es lo mejor": "audio/ui/ac44e3033b.mp3",
  "Me alejo": "audio/ui/a6382f7761.mp3",
  "Lo toco igual": "audio/ui/1a6b8dd064.mp3",
  "Aviso a un adulto": "audio/ui/5238a3c636.mp3",
  "¿Cómo me cuido?": "audio/ui/88cb45ff01.mp3",
  "Lavarme las manos": "audio/ui/af63d10ff9.mp3",
  "No comer cosas del suelo": "audio/ui/74ea93c90a.mp3",
  "Tocar todo sucio": "audio/ui/dda2a84498.mp3",
  "¡Maestro del Reino de las Emociones!": "audio/ui/af43135327.mp3",
  "Siguiente reto": "audio/ui/d8e7d6c5af.mp3",
  "Seguir intentando": "audio/ui/7e7e0e264e.mp3",
  "Continuar": "audio/ui/b8cb6f8bec.mp3",
  "Ya escuché, continuar": "audio/ui/abc77cca1f.mp3",
  "Volver al mapa": "audio/ui/568d24469e.mp3",
  "Ver mi premio": "audio/ui/a2e6ee6540.mp3",
  "Jugar de nuevo": "audio/ui/e6f749f5f1.mp3",
  "Confirmar": "audio/ui/81b4b67ff8.mp3",
  "Entendido": "audio/ui/ee24e6fed2.mp3",
  "empezar": "audio/ui/7f5a9bed5d.mp3",
  "¡Muy bien!": "audio/ui/2c0ab017ea.mp3",
  "Casi… revisa bien tu selección": "audio/ui/72cd440c9e.mp3",
  "Mmm… esa no es. Inténtalo de nuevo": "audio/ui/f8654104be.mp3",
  "Esa opción no ayuda mucho… prueba otra": "audio/ui/3c45b8e19e.mp3",
  "Piensa otra vez en la historia… ¿cuál será?": "audio/ui/1d63d0a124.mp3",
  "Recuerda el semáforo: primero parar": "audio/ui/2268d77d50.mp3",
  "Esa va en la otra caja, mira bien": "audio/ui/08ecfd9d1d.mp3",
  "El reino de las emociones necesita tu ayuda": "audio/ui/71f3b1d2e4.mp3",
  "Mapa del Reino": "audio/ui/d4e5442cac.mp3"
};